$(document).ready(function(){
    $("#email").click(function(){
        console.log($("#email").val())
    })
    $("#password").click(function(){
        console.log($("#password").val())
    })
})
$(document).ready(function(){
    $("#create").click(function(){
        console.log($("#create").val())
    })
})